export const theme = {
  colors: {
    // Layered neutral surfaces for subtle depth.
    bg: "#f8fafc",
    surface1: "#ffffff",
    surface2: "#f8fafc",
    surface3: "#f1f5f9",
    card: "#ffffff",
    cardMuted: "#f1f5f9",
    cardPressed: "#e2e8f0",
    text: "#111827",
    textInverse: "white",
    muted: "#475569",
    border: "#cbd5e1",
    borderStrong: "#94a3b8",
    divider: "#ddd",
    primary: "#2563eb",
    primaryMuted: "#dbeafe",
    success: "#16a34a",
    successBg: "#dcfce7",
    error: "#b91c1c",
    errorBg: "#fee2e2",
    errorBorder: "#fecaca",
    warning: "#f59e0b",
    shadow: "#000",
    overlaySoft: "rgba(0,0,0,0.03)",
    overlayBackdrop: "rgba(0,0,0,0.35)",
    focusRing: "#93c5fd",
    disabledBg: "#e2e8f0",
    disabledText: "#64748b",
  },
  radius: 12,
  radiusLg: 16,
  radiusSm: 10,
  spacing: (n: number) => 8 * n,
  typography: {
    titleXl: { fontSize: 28, fontWeight: "700" as const, lineHeight: 34 },
    titleLg: { fontSize: 24, fontWeight: "700" as const, lineHeight: 30 },
    titleMd: { fontSize: 21, fontWeight: "700" as const, lineHeight: 27 },
    sectionTitle: { fontSize: 16, fontWeight: "600" as const },
    body: { fontSize: 16, lineHeight: 22 },
    caption: { fontSize: 12, lineHeight: 16 },
  },
  elevation: {
    subtle: {
      shadowColor: "#000",
      shadowOpacity: 0.04,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    card: {
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 5,
    },
    floating: {
      shadowColor: "#000",
      shadowOpacity: 0.12,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 8,
    },
  },
};
