export const theme = {
  colors: {
    bg: "white",
    card: "white",
    cardMuted: "#f3f4f6",
    cardPressed: "#f9fafb",
    text: "#111827",
    textInverse: "white",
    muted: "#6b7280",
    border: "#e5e7eb",
    divider: "#ddd",
    primary: "#2563eb",
    success: "#16a34a",
    successBg: "#dcfce7",
    error: "#b91c1c",
    errorBg: "#fee2e2",
    errorBorder: "#fecaca",
    warning: "#f59e0b",
    shadow: "#000",
    overlaySoft: "rgba(0,0,0,0.03)",
    overlayBackdrop: "rgba(0,0,0,0.35)",
  },
  radius: 12,
  spacing: (n: number) => 8 * n,
  typography: {
    titleXl: { fontSize: 26, fontWeight: "700" as const },
    titleLg: { fontSize: 24, fontWeight: "700" as const },
    titleMd: { fontSize: 22, fontWeight: "700" as const },
    sectionTitle: { fontSize: 16, fontWeight: "600" as const },
    body: { fontSize: 16 },
    caption: { fontSize: 12 },
  },
  elevation: {
    card: {
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 5,
    },
  },
};
